name: CD

on:
  push:
    # Trigger the workflow every time you push to the `trunk` branch
    branches:
      - trunk
    paths:
      - .github/workflows/*
      - packages/abi.js/**
      - website/**
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    working-directory: ./website

jobs:
  deploy:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        bun-version: [1.1.24]

    environment:
      name: github-pages
      url: https://abi-js.github.io

    name: ğŸš€ Deploy abi.js.org with Bun@${{ matrix.bun-version }} under ${{ matrix.operating-system }}

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ‰ Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: âš¡ï¸ Install dependencies
        run: bun install

      - name: ğŸ“¦ Build the website
        run: bun run build

      - name: ğŸ“‚ Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/trunk'
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: website/dist
          destination_dir: .
          external_repository: abi-js/abi-js.github.io
