name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ${{ matrix.operating-system }}

    defaults:
      run:
        working-directory: ./packages/website

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        node-version: [20.13]
        pnpm-version: [9.1]

    name: ğŸ§ª CI Abi's website on Node@${{ matrix.node-version }}-${{ matrix.operating-system }}

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ‰ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: âœ¨ Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: ${{ matrix.pnpm-version }}

      - name: âš¡ï¸ Install dependencies
        run: pnpm install

      - name: âœ… Check types
        run: pnpm check

      - name: ğŸ± Build assets
        run: pnpm build

