name: Deploy

on:
  push:
    branches:
      - trunk

  workflow_run:
    workflows: [Release]
    types: [completed]
    branches: [trunk]

jobs:
  frontend:
    runs-on: ${{ matrix.operating-system }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    defaults:
      run:
        working-directory: ./www/apps/frontend

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        bun-version: [1.1.25]

    name: ğŸ“¦ï¸ Build the frontend on ${{ matrix.operating-system }} using Bun@${{ matrix.bun-version }}

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: âš¡ï¸ Install dependencies
        run: bun install

      - name: ğŸ± Build assets
        run: bun run build

      - name: ğŸ—ƒï¸ List distribution files
        run: ls -R dist

      - name: ğŸšš Upload distribution files
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: www/apps/frontend/dist

  deploy:
    needs: frontend
    runs-on: ${{ matrix.operating-system }}

    environment:
      name: production
      url: https://abi.deno.dev

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: ./www/apps/backend

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        deno-version: [1.45.5]

    name: ğŸš€ Deploy abi.deno.dev to ${{ matrix.operating-system }} on Deno-${{ matrix.deno-version }}

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ”¨ Configure Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: ğŸšš Download distribution files
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: www/apps/frontend/dist

      - name: ğŸ—ƒï¸ List distribution files
        run: ls -R ../frontend/dist

      - name: ğŸ“‚ Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: abi
          entrypoint: backend/abi.ts
          root: www/apps
